using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using System.IO;
using System.Text;
using Miventech.NativeVoxReader;
using Miventech.NativeVoxReader.Data;
using Miventech.NativeVoxReader.Abstract;
using Miventech.NativeVoxReader.VoxRenderer;
using System;
using Miventech.NativeVoxReader.Readers;
namespace Miventech.NativeVoxReader
{
    public class VoxReader : MonoBehaviour
    {
        public bool UseRelativePath = true;
        public string FilePathVox;

        // Cache for editor/runtime use
        public VoxFile loadedVoxFile;

        public VoxCreateObjectAbstract meshBuilder;


        [ContextMenu("Read Vox File")]
        public void ReadVoxFile()
        {
            var PathToRead = FilePathVox;
            if (UseRelativePath)
            {
                PathToRead = Path.Combine(Application.dataPath, FilePathVox);
            }

            if (string.IsNullOrEmpty(PathToRead) || !File.Exists(PathToRead))
            {
                Debug.LogError("File path is invalid or file does not exist.");
                return;
            }

            if (meshBuilder == null)
            {
                Debug.LogError("Mesh Builder is not assigned.");
                return;
            }

            string extension = Path.GetExtension(PathToRead).ToLower();
            loadedVoxFile = null;
            foreach (var ReaderClass in BaseReaderFile.GetAllReaders())
            {
                if (!ReaderClass.IsValidFile(PathToRead)) continue;
                var parsedFile = ReaderClass.Read(PathToRead);
                if (parsedFile == null) continue;
                loadedVoxFile = parsedFile;
                break; // The first reader that successfully parses the file wins.
            }
            if (loadedVoxFile == null)
            {
                Debug.LogError($"No suitable reader found (unsupported extension: {extension}) for file: {PathToRead}");
                return;
            }

            RemoveInternalObject();

            foreach (VoxModel voxModel in loadedVoxFile.models)
            {
                meshBuilder.BuildObject(voxModel, loadedVoxFile.palette.ToColor32Array());
            }
        }



        private void RemoveInternalObject()
        {
            // Only remove children generated by the voxel builders ("VoxModel...").
            // Destroying every child would also wipe user objects parented to this one.
            for (int i = transform.childCount - 1; i >= 0; i--)
            {
                Transform child = transform.GetChild(i);
                if (!child.name.StartsWith("VoxModel")) continue;
                if (Application.isEditor)
                    DestroyImmediate(child.gameObject);
                else
                    Destroy(child.gameObject);
            }
        }

    }
}

